Keep destination path as a byte string
File paths are not guaranteed to be valid Unicode strings, so Beets
expects them to be of type bytes() rather than str().

Without this fix, the call to `beets.util.unique_path()` can crash with
the following traceback:

   Traceback (most recent call last):
      File "/home/sam/.local/bin/beet", line 11, in <module>
        load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
      File "/home/sam/.local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1256, in main
        _raw_main(args)
      File "/home/sam/.local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1245, in _raw_main
        plugins.send('cli_exit', lib=lib)
      File "/home/sam/.local/lib/python3.6/site-packages/beets/plugins.py", line 476, in send
        result = handler(**arguments)
      File "/home/sam/.local/lib/python3.6/site-packages/beets/plugins.py", line 140, in wrapper
        return func(*args, **kwargs)
      File "/home/sam/.local/lib/python3.6/site-packages/beetsplug/copyartifacts.py", line 127, in process_events
        self.process_artifacts(item['files'], item['mapping'], False)
      File "/home/sam/.local/lib/python3.6/site-packages/beetsplug/copyartifacts.py", line 161, in process_artifacts
        dest_file = beets.util.unique_path(dest_file)
      File "/home/sam/.local/lib/python3.6/site-packages/beets/util/__init__.py", line 548, in unique_path
        match = re.search(br'\.(\d)+$', base)
      File "/usr/lib64/python3.6/re.py", line 182, in search
        return _compile(pattern, flags).search(string)
    TypeError: cannot use a bytes pattern on a string-like object

This crash would only occur if the unique_path() function found that the
destination path already existed.

Fixes #44